// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type IdentifierType string

const (
	IdentifierTypeNationalID IdentifierType = "NATIONAL_ID"
	IdentifierTypePassport   IdentifierType = "PASSPORT"
)

var AllIdentifierType = []IdentifierType{
	IdentifierTypeNationalID,
	IdentifierTypePassport,
}

func (e IdentifierType) IsValid() bool {
	switch e {
	case IdentifierTypeNationalID, IdentifierTypePassport:
		return true
	}
	return false
}

func (e IdentifierType) String() string {
	return string(e)
}

func (e *IdentifierType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IdentifierType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IdentifierType", str)
	}
	return nil
}

func (e IdentifierType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
