package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	"github.com/oryx-systems/smartduka/pkg/smartduka/application/enums"
	"github.com/oryx-systems/smartduka/pkg/smartduka/domain"
	"github.com/oryx-systems/smartduka/pkg/smartduka/presentation/graph/generated"
)

// MiddleName is the resolver for the middleName field.
func (r *userResolver) MiddleName(ctx context.Context, obj *domain.User) (string, error) {
	panic(fmt.Errorf("not implemented: MiddleName - middleName"))
}

// Flavour is the resolver for the flavour field.
func (r *userResolver) Flavour(ctx context.Context, obj *domain.User) (enums.Flavour, error) {
	panic(fmt.Errorf("not implemented: Flavour - flavour"))
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
